version: 2

jobs:
  "Execute tests":
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path .bundle
      - run: bundle exec rake

workflows:
  version: 2
  build:
    jobs:
      - "Execute tests"
